TIMEZONE = 'Australia/Melbourne'
BOT_CHANNEL = 'ctf-news'
OTHER_CHANNELS = ['bot-spam']
# DB_URI = 'mysql+pymysql://root:ctfd@db/ctfd'
DB_URI = 'mysql+pymysql://root:ctfd@0.0.0.0:3306/ctfd'
CTFD_MODE = 'teams'  # users or teams
CATCH_MODE = 'all'  # all or user or admin
LIMIT_SIZE = 1000
MEDALS = [':first_place:', ':second_place:', ':third_place:']
TOKEN = 'token'
